name: tracking
channels:
  - conda-forge
  - defaults
dependencies:
  - asttokens=3.0.0=pyhd8ed1ab_1
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.10.5=h4c7d964_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - debugpy=1.8.17=py310h699e580_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=7.0.1=pyh6dadd2b_0
  - ipython=8.37.0=pyha7b4d00_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyh6dadd2b_0
  - krb5=1.21.3=hdf4eb48_0
  - libexpat=2.7.1=hac47afa_0
  - libffi=3.4.4=hd77b12b_1
  - liblzma=5.8.1=h2466b09_2
  - liblzma-devel=5.8.1=h2466b09_2
  - libsodium=1.0.20=hc70643c_0
  - libsqlite=3.50.4=hf5d6505_0
  - libzlib=1.3.1=h02ab6af_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.5.4=h725018a_0
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.5=pyhcf101f3_0
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.2=pyhc872135_1
  - platformdirs=4.5.0=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.0=py310h29418f3_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.10.19=hcb012bd_1_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.10=8_cp310
  - pywin32=311=py310h282bd7d_1
  - pyzmq=27.1.0=py310h535538e_0
  - setuptools=80.9.0=py310haa95532_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.50.2=hda9a48d_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.15=hf199647_0
  - tornado=6.5.2=py310h29418f3_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=py310haa95532_0
  - xz=5.8.1=h208afaa_2
  - xz-tools=5.8.1=h2466b09_2
  - zeromq=4.3.5=h5bddc39_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - accelerate==1.10.1
      - annotated-types==0.7.0
      - anyio==4.11.0
      - anywidget==0.9.18
      - bbox-visualizer==0.2.2
      - beautifulsoup4==4.14.2
      - boxmot==15.0.9
      - bytecode==0.15.1
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - click==8.3.0
      - clip==0.2.0
      - contourpy==1.3.2
      - cycler==0.12.1
      - cython==3.1.4
      - defusedxml==0.7.1
      - einops==0.8.1
      - fairscale==0.4.13
      - filelock==3.20.0
      - filetype==1.2.0
      - filterpy==1.4.5
      - fonttools==4.60.1
      - fsspec==2025.9.0
      - ftfy==6.3.1
      - gdown==5.2.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - grpcio==1.76.0
      - h11==0.16.0
      - h2==4.3.0
      - hpack==4.1.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.35.3
      - hyperframe==6.1.0
      - idna==3.7
      - ipywidgets==8.1.7
      - jinja2==3.1.6
      - joblib==1.5.2
      - jupyter-bbox-widget==0.6.0
      - jupyterlab-widgets==3.0.15
      - kiwisolver==1.4.9
      - lapx==0.6.0
      - loguru==0.7.3
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - mplcursors==0.7
      - mpmath==1.3.0
      - networkx==3.4.2
      - ninja==1.13.0
      - numpy==2.2.6
      - open-clip-torch==3.2.0
      - opencv-contrib-python==4.12.0.88
      - opencv-python-headless==4.10.0.84
      - paho-mqtt==2.1.0
      - pandas==2.3.3
      - peft==0.17.1
      - pi-heif==1.1.1
      - pillow==12.0.0
      - pillow-avif-plugin==1.5.2
      - polars==1.34.0
      - polars-runtime-32==1.34.0
      - polygraphy==0.49.26
      - portalocker==3.2.0
      - protobuf==6.33.0
      - psygnal==0.15.0
      - pycocotools==2.0.10
      - pydantic==2.12.3
      - pydantic-core==2.41.4
      - pygame==2.6.1
      - pylabel==0.1.55
      - pyparsing==3.2.5
      - pyqt5==5.15.11
      - pyqt5-qt5==5.15.2
      - pyqt5-sip==12.17.1
      - pysocks==1.7.1
      - python-dotenv==1.1.1
      - pytz==2025.2
      - pyyaml==6.0.3
      - qdrant-client==1.15.1
      - regex==2024.11.6
      - requests==2.32.5
      - requests-toolbelt==1.0.0
      - rf100vl==1.1.0
      - rfdetr==1.3.0
      - roboflow==1.2.11
      - safetensors==0.6.2
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.8
      - supervision==0.26.1
      - sympy==1.13.1
      - threadpoolctl==3.6.0
      - timm==1.0.20
      - tokenizers==0.13.3
      - torch==2.5.1+cu121
      - torchvision==0.20.1+cu121
      - tqdm==4.67.1
      - transformers==4.31.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - urllib3==2.5.0
      - uv==0.9.3
      - widgetsnbextension==4.0.14
      - win32-setctime==1.2.0
      - yacs==0.1.8
prefix: C:\Users\hthek\anaconda3\envs\tracking
